### ISSUE TITLE
Adding course_ids that do not exist still create enrollment entries

### ISSUE THREAD

**Issue by patrickspensieri** [n2chao/SOEN341#103]
Was testing the code for adding courses, and found an issue in `EnrollmentController.php`. The Validator does not work properly, as it should only create an `enrollment` entry if the given `course_id` exists.

Here, `$data` is an array of given `course_id` to be added. See documentation on validation.

[https://laravel.com/docs/5.4/validation#rule-exists](url)

```
Validator::make($data, [    //rule validation
            'add_course_ids' => [
                'unique',
                'required',
                'integer',
                'exists:courses,id',    //exists in courses table, column id
            ],
]);
```

**Comment by n2chao** [comment]
Fixed in PR #111
