### ISSUE TITLE
#59 Create bookTimeTraits

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#107]
This task is to crate a function that removes booked meeting hours from a users available hours so that the matching algorithm takes into account meetings that already exist. The result is that the times where a user has a meeting booked to not show on the page displaying possible available times for selection by another user.

**Comment by alimouawieh** [comment]
![capture4](https://cloud.githubusercontent.com/assets/25372909/25074961/adce4afc-22d6-11e7-99f8-b2bf5b6e4bca.PNG)
