### ISSUE TITLE
Sidebar should properly link to each page.

### ISSUE THREAD

**Issue by nemotime** [n2chao/SOEN341#115]
The links for most buttons on the side bar currently link to` "#"`. Now that most pages are done, a link can be created between every page on the website.

**Comment by nemotime** [comment]
Issue closed by pull request #142

**Comment by alimouawieh** [comment]
![capture3](https://cloud.githubusercontent.com/assets/25372909/25074930/9aaba8a8-22d5-11e7-8dc4-d4c0bde7beeb.PNG)
