### ISSUE TITLE
#123 Create title in registration

### ISSUE THREAD

**Issue by ho-man-chan** [n2chao/SOEN341#119]
User will be able to set their title in the registration form
ex: TA, TEACHER, STUDENT

**Comment by prich28** [comment]
@ho-man-chan This feature does not work yet when registering with Facebook.

**Comment by alimouawieh** [comment]
![capture2](https://cloud.githubusercontent.com/assets/25372909/25074902/fd73d498-22d4-11e7-919c-81ae9a6e7e7e.PNG)
