### ISSUE TITLE
#43 User can choose their roll/'title' on the page when they register

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#123]
User Story:

The user can choose which roll they will take on when they register for the website. They will have the option of choosing to be a Student, TA or Teacher.

**Comment by alimouawieh** [comment]
![capture](https://cloud.githubusercontent.com/assets/25372909/25055705/71b669f0-2132-11e7-9151-95d01a9fd295.PNG)

**Comment by KarineZhang** [comment]
Hi @alimouawieh , 
I noticed that there are few mistakes in your description, do you mind copy pasting this in?
" Description : Whenever a new user wants to register with a new account on Buddy Up, he/she can select to register either as a Teacher.Teacher Assistant or as a Student from the given drop down list "
Thank you ~

**Comment by alimouawieh** [comment]
![issue 123](https://cloud.githubusercontent.com/assets/25372909/25057795/fa5fd8a0-2140-11e7-8f62-23fb6c7a8ac2.PNG)
