### ISSUE TITLE
User Story: The list of available times must exclude booked meetings for each user

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#130]
Story:

As a user, after I've selected an instructor to meet with, and the week-day I would like to make the meeting, I only want to see times which this instructor is free. In other words, if the instructor has a meeting already booked for a possible matched free time, I don't want that time to be available to me, the user, to select.

**Comment by prich28** [comment]
This feature has now been merged to the master branch. Closing user story.

**Comment by AmadouF** [comment]
![issue130](https://cloud.githubusercontent.com/assets/25256114/24937708/8053f36c-1f00-11e7-8811-82c893fcb942.PNG)
