### ISSUE TITLE
User Story: Only My Teachers

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#146]
As a user, when I go to make an appointment with a teacher, I only want the teachers or teaching assistants that are associated with my classes to appear in the initial list.

**Comment by patrickspensieri** [comment]
See pull request #150

**Comment by n2chao** [comment]
![acceptance_146](https://cloud.githubusercontent.com/assets/10326583/24937799/24d5a066-1f01-11e7-8b59-720686e1d782.PNG)
