### ISSUE TITLE
Embedded Teamviewer in website

### ISSUE THREAD

**Issue by KarineZhang** [n2chao/SOEN341#18]
● Students may book an Online Appointment with TA/Teachers during the booking process. 
● This will enhance students learning process, especially for the ones who live far away from school, for the ones who have a busy schedule or students with disabilities. 

https://www.teamviewer.com/en/help/421-how-can-i-embed-teamviewer-in-my-website

**Comment by prich28** [comment]
This feature will not be pursued. Closing issue.
