### ISSUE TITLE
#30 Create a front-end page for course selection

### ISSUE THREAD

**Issue by KarineZhang** [n2chao/SOEN341#188]
- User can add up to 7 courses by typing course name i.e SOEN341
- User must add at least 1 course before submitting, else it will prompt an alert message
Refer to user story #30

**Comment by KarineZhang** [comment]
#80

**Comment by prich28** [comment]
This issue was merged to master in pull request #80

**Comment by KarineZhang** [comment]
Closing task, completed in pull request #80
