### ISSUE TITLE
#34 A user can select a class to find a buddy to study with

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#38]
User Story:
User can select and confirm a selection, from a list of their current classes, a class they would like to find a buddy for.

- [ ] creating the page layout for selecting a class to study, based on the template.

**Comment by prich28** [comment]
Assessed at the beginning of SPRINT2

Associated Tasks:
-Create UI (front end) with php to display all possible classes
-Create form for submitting selections

Difficulty:
5

Priority:
LOW - Mainly for sprint three and will be based off a page for adding courses to a profile.

Risk:
MED - Choosing a class to find a budy to study with is important, however the front end for this page will be mostly based of of the page to add a course to the user profile.

**Comment by prich28** [comment]
Making this sprint 4 and including the back end portion to this story.

Back End requirements:

- [ ] Create DB query in order to retrieve the class information for the given student so that they can select it as the initial step in finding a buddy.

**Comment by patrickspensieri** [comment]
See pull request #132

**Comment by AmadouF** [comment]
![issue 38](https://cloud.githubusercontent.com/assets/25256114/24937836/55ea0b6a-1f01-11e7-9d5e-d737cb1c1186.PNG)
