### ISSUE TITLE
User should be able to register and log in using Facebook

### ISSUE THREAD

**Issue by patrickspensieri** [n2chao/SOEN341#45]
User Story:
User can login to their account using a login with Facebook option.

**Comment by prich28** [comment]
Assessed at the beginning of SPRINT 2 (was already in progress)

Associated Tasks:
-Add socialite dependancy
-Connect it to the user table for adding a user.

Difficulty:
5

Priority:
LOW - (already almost complete at the beginning of sprint2)

Risk:
LOW - the user can register with email and password. Facebook sign in is an extra feature.

**Comment by patrickspensieri** [comment]
Completed, see Pull Request #68

**Comment by n2chao** [comment]
![acceptance_45](https://cloud.githubusercontent.com/assets/10326583/24937789/13949744-1f01-11e7-9a54-53870da86a42.PNG)
