### ISSUE TITLE
#30 User shall select a course, and the course is added to the list for adding to their profile

### ISSUE THREAD

**Issue by patrickspensieri** [n2chao/SOEN341#46]
User Story:
From the list of available courses, the user can select a course that will be added to their list of enrolled courses.

To track progress, refer to Epic #30

**Comment by prich28** [comment]
Assessed at the beginning of SPRINT2

Associated Tasks:
-create a DB table of courses
-create controller function to send course information to page
-create front end so a course can be selected
-create front end for course selection to appear in a pending list

Difficulty:
5

Priority:
HIGH - Required for initializing a profile and taking advantage of the main fucntion of the app.

Risk:
HIGH - Essential for users to add courses to their profile for matching with another user later on.

**Comment by prich28** [comment]
![at 46](https://cloud.githubusercontent.com/assets/23619757/24536287/71d4d4b2-15a7-11e7-8593-62beca914ca7.png)

**Comment by prich28** [comment]
![acctest 46](https://cloud.githubusercontent.com/assets/23619757/24536317/a07d60ae-15a7-11e7-8d34-58fec5306a50.png)

**Comment by KarineZhang** [comment]
#30 #188

**Comment by KarineZhang** [comment]
#188 #80

**Comment by KarineZhang** [comment]
#30 #188

**Comment by KarineZhang** [comment]
#188

**Comment by KarineZhang** [comment]
#30 #80 #188

**Comment by KarineZhang** [comment]
#80

**Comment by KarineZhang** [comment]
#188 #80

**Comment by KarineZhang** [comment]
#188 #80

**Comment by KarineZhang** [comment]
#80

**Comment by KarineZhang** [comment]
#80

**Comment by KarineZhang** [comment]
#188

**Comment by KarineZhang** [comment]
#80 Add course selection layout merged

**Comment by KarineZhang** [comment]
Create a front-end page for course selection issue #188

**Comment by KarineZhang** [comment]
#188
