### ISSUE TITLE
#30 User shall confirm the list of selected classes to be added to their schedule

### ISSUE THREAD

**Issue by patrickspensieri** [n2chao/SOEN341#48]
User Story:
User shall confirm the list of selected classes to be added to their schedule

To track progress, refer to Epic #30

**Comment by prich28** [comment]
Assessed at the beginning of SPRINT2

Associated Tasks:
-Create front end sumbission form
-design controller to submit the data to the database.
-create necessary DB tables for storing/accessing courses

Difficulty:
5

Priority:
HIGH - Needed for matching algorithm

Risk:
HIGH - Essential for users to add courses to their profile for matching with another user later on.

**Comment by patrickspensieri** [comment]
![issue48](https://cloud.githubusercontent.com/assets/8960233/24940925/5d053812-1f14-11e7-9124-4d798aba88c7.jpg)
