### ISSUE TITLE
Users can add or remove free time from their schedule

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#49]
EPIC:

There is a page to adjust the student/user's free time.
The user selects blocks of time, in 15 min segments on a weekly schedule, that they are free to study.
They can confirm the selections by saving.

**Comment by ho-man-chan** [comment]
View free-time
![screen shot 2017-04-11 at 11 27 22 pm](https://cloud.githubusercontent.com/assets/21694293/24939969/80dec7f4-1f0e-11e7-8c5c-1b98a7171468.png)

Edit Free-time by unchecking
![screen shot 2017-04-11 at 11 27 12 pm](https://cloud.githubusercontent.com/assets/21694293/24939971/80e0225c-1f0e-11e7-9ccc-b931f54b6a96.png)

Edit Free-time by checking 
![screen shot 2017-04-11 at 11 26 56 pm](https://cloud.githubusercontent.com/assets/21694293/24939968/80de27ae-1f0e-11e7-8e37-2e3f7e7b3b00.png)

View free-time after change
![screen shot 2017-04-11 at 11 26 46 pm](https://cloud.githubusercontent.com/assets/21694293/24939970/80df7e2e-1f0e-11e7-82dc-1dfd8fc98b1c.png)

**Comment by ho-man-chan** [comment]
![screen shot 2017-04-12 at 12 18 28 am](https://cloud.githubusercontent.com/assets/21694293/24941087/b80ebae8-1f15-11e7-8747-c59249b93de4.png)
