### ISSUE TITLE
#49 User can select free time to add to their schedule

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#50]
User Story:
User selects a start time and end time and a day of the week and adds it to the schedule with a confirmation. The time gets added to a list.

**Comment by prich28** [comment]
Assessed at the beginning of SPRINT 2

Associated Tasks:
-Front end design
-create a mechanism for adding a selection of time visibly

Difficulty:
5

Priority:
HIGH - Allows for entering free time. Necessary for matching algorithm

Risk:
MED - The ability to add a selected time is important but this is a front end task and testing can still be done with a more primative means of addition or removal.

**Comment by ho-man-chan** [comment]
this task was completed in pull request #91

**Comment by ho-man-chan** [comment]
View free-time
![screen shot 2017-04-11 at 11 27 22 pm](https://cloud.githubusercontent.com/assets/21694293/24939969/80dec7f4-1f0e-11e7-8c5c-1b98a7171468.png)

Edit Free-time by unchecking
![screen shot 2017-04-11 at 11 27 12 pm](https://cloud.githubusercontent.com/assets/21694293/24939971/80e0225c-1f0e-11e7-9ccc-b931f54b6a96.png)

Edit Free-time by checking 
![screen shot 2017-04-11 at 11 26 56 pm](https://cloud.githubusercontent.com/assets/21694293/24939968/80de27ae-1f0e-11e7-8e37-2e3f7e7b3b00.png)

View free-time after change
![screen shot 2017-04-11 at 11 26 46 pm](https://cloud.githubusercontent.com/assets/21694293/24939970/80df7e2e-1f0e-11e7-82dc-1dfd8fc98b1c.png)

**Comment by ho-man-chan** [comment]
![screen shot 2017-04-12 at 12 18 33 am](https://cloud.githubusercontent.com/assets/21694293/24941093/c5f72762-1f15-11e7-9827-3100545e0dac.png)
