### ISSUE TITLE
#49 User can save/confirm changes to free time

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#52]
User Story:

On the add/remove free time page, user can save changes to the list of available free time by pressing a confirmation (save) button.

**Comment by prich28** [comment]
Assessed at the beginning of SPRINT 2

Associated Tasks:
-button and associated form for submitting confirmation
-create necessary DB tables for storing and accessing times
-create controller to upate database with selected times

Difficulty Level:
8 - Ideally all of the free time selected has to be stored in single-variable fashion to reduce the complexity of the database. The current idea involves a an string of 1 and 0.

Priority:
HIGH - Allows for entering free time. Necessary for matching algorithm

Risk:
HIGH - Necessary for the algorithm for matchng with another site user.

**Comment by ho-man-chan** [comment]
this task was completed in pull request #91

**Comment by n2chao** [comment]
![capture](https://cloud.githubusercontent.com/assets/10326583/24943336/32702fe8-1f24-11e7-85a9-d62813a691a2.PNG)

**Comment by prich28** [comment]
See issues #51 and #50 for Acceptance testing.
