### ISSUE TITLE
Footer does not stick to bottom when scrolling through long pages

### ISSUE THREAD

**Issue by patrickspensieri** [n2chao/SOEN341#79]
![screen shot 2017-02-14 at 1 25 29 pm](https://cloud.githubusercontent.com/assets/8960233/22942833/20146fd6-f2b9-11e6-90e0-f59b3933417b.jpg)

**Comment by nemotime** [comment]
Read about sticky footers. I can maybe come up with a hot patch if someone else doesn't.
