### ISSUE TITLE
Users can enter their weekly availabilities

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#8]
Enter courses, date, time, duration of classes.

**Comment by ho-man-chan** [comment]
![screen shot 2017-04-11 at 11 27 22 pm](https://cloud.githubusercontent.com/assets/21694293/24939969/80dec7f4-1f0e-11e7-8c5c-1b98a7171468.png)
![screen shot 2017-04-11 at 11 27 12 pm](https://cloud.githubusercontent.com/assets/21694293/24939971/80e0225c-1f0e-11e7-9ccc-b931f54b6a96.png)
![screen shot 2017-04-11 at 11 26 56 pm](https://cloud.githubusercontent.com/assets/21694293/24939968/80de27ae-1f0e-11e7-8e37-2e3f7e7b3b00.png)
![screen shot 2017-04-11 at 11 26 46 pm](https://cloud.githubusercontent.com/assets/21694293/24939970/80df7e2e-1f0e-11e7-82dc-1dfd8fc98b1c.png)

**Comment by ho-man-chan** [comment]
![screen shot 2017-04-12 at 12 18 18 am](https://cloud.githubusercontent.com/assets/21694293/24941079/aa8536fe-1f15-11e7-80d7-b53d74e9bc30.png)
