### ISSUE TITLE
#34 User sees students whose free time matches theirs for the course they chose

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#81]
User Story:

After the user chooses a course to study for, the app displays the students who are studying that same course and whose free time matches the user.

**Comment by patrickspensieri** [comment]
I have a question concerning the size of each study group. As a user, if I select a class to study for, and then select a student, that sends a pending meeting request to the student. Once he confirms, then the meeting is confirmed.

What happens after that?

Can a study group consist of more than two students?

**Comment by patrickspensieri** [comment]
See pull request #132

**Comment by alimouawieh** [comment]
![issue 81](https://cloud.githubusercontent.com/assets/25372909/24939497/c3a7ab30-1f0b-11e7-88ae-7bf2cdb2f8b1.PNG)
