### ISSUE TITLE
Students can schedule a meeting with fellow students

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#9]
Pick a course you want to study. Show matches of other students who are taking the course. Show their available times that match with your available times.

**Comment by prich28** [comment]
This issue is being replaced/continued by issue #34.

**Comment by alimouawieh** [comment]
![issue 9](https://cloud.githubusercontent.com/assets/25372909/24939446/58f3dd04-1f0b-11e7-938d-18717125caca.PNG)
