### ISSUE TITLE
#123 Adding a roll/'title' on the page when they register

### ISSUE THREAD

**Issue by prich28** [n2chao/SOEN341#94]
User Story:

The user can choose which roll they will take on when they register for the website. They will have the option of choosing to be a Student, TA or Teacher.

**Comment by KarineZhang** [comment]
![register_as](https://cloud.githubusercontent.com/assets/25305753/23335673/20bbff9e-fb88-11e6-8edd-bcece5682047.png)

**Comment by KarineZhang** [comment]
![register_as](https://cloud.githubusercontent.com/assets/25305753/23335690/91d01940-fb88-11e6-9d95-a615d98dceba.png)
 @prich28 Hi Paul, is this how the title selection should look like? I wrote down the label as "Register As"

**Comment by KarineZhang** [comment]
Just a quick question, if the users are selecting their "title" at the registration page, then does it mean that each user "Student, Teacher Assistant & Teacher " shall have their own dashboard?

**Comment by prich28** [comment]
The drop down menu looks really good! I think Nathan wanted to make a page where you can change it after you sign in as well. But this is nice. 

No I think the Dashboard will be the same. Although maybe a teacher or a TA won't have "find a buddy" option.. but maybe they should.

**Comment by KarineZhang** [comment]
@prich28 Thanks Paul! Oh okay, I also talked about it with Nathan, and he said it's okay to keep the drop down menu on registration page for now.

**Comment by prich28** [comment]
Keeping the hour time length on this user story as there is no task/subtask associated with the story.

**Comment by prich28** [comment]
This feature has been added and works properly. Closing.
